name: Deploy bcd updates data to s3

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Notes"
        required: false
        default: ""

jobs:
  deploy-stage-updates:
    name: Deploy to stage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: updates

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: "https://registry.npmjs.org/"
          cache: npm
      - run: npm ci
      - run: npm run update standalone
      - name: Configure AWS credentials for stage
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGE_AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2
      - run: aws s3 sync --acl public-read --delete v0/ s3://mdn-content-stage/main/bcd/updates/v0
